[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"

[leffat]
title = "Päivän TV-elokuvat"
url = "https://www.iltapulu.fi/elokuvat"
entrySelector = ".day-wrapper > ul li"
titleSelector = "h3"
linkSelector = "h3 a"

[telsu]
title = "Leffat tänään"
url = "https://www.telsu.fi/elokuvat"
entrySelector = ".dets > div"
titleSelector = "h2"
linkSelector = "a.othprg"
matchOneOf = ["tänään"]

#div.dets:nth-child(2) > div:nth-child(1)
#div.dets:nth-child(2)
#div.dets:nth-child(3) > div:nth-child(1) > div:nth-child(3) > a:nth-child(3)
#html body div#res div.dets.stat div.c div.f a.othprg