[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"

[leffat]
title = "Päivän TV-elokuvat
url = "https://www.iltapulu.fi/elokuvat"
entrySelector = ".day-wrapper > ul li"
titleSelector = "h3"
linkSelector = "h3 a"


#mp-dyk > ul:nth-child(2) > li:nth-child(1)
#div.day-wrapper:nth-child(2) > ul:nth-child(2) > li:nth-child(1)
#mp-dyk
